name: doxygen

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  doxygen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get install -y doxygen

      - uses: mattnotmitt/doxygen-action@v1.1.0
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: html
