name: nightly

on:
  # Run once daily at 8:45 PM.
  schedule:
    - cron: "45 20 * * */1"

  # Allow manually-triggered runs.
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml

  # Generate a nightly tag if build and test jobs succeed.
  tag:
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
      - name: Get today's date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create nightly tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/nightly-${{ steps.date.outputs.date }}",
              sha: context.sha
            })
